version: '3.8'

services:
  client:
    image: node:18
    container_name: immo-client
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
