version: '3.7'

services:
  immo-api-php: 
    image: php:8.2
    container_name: immo-api-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:9000 -t ./public

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    