version: '3.8'

services:
  admin:
    image: node:18
    container_name: immo-admin
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
